// @generated automatically by Diesel CLI.

diesel::table! {
    ingredients (id) {
        id -> Int4,
        name -> Varchar,
        branded -> Bool,
        sub_ingredients -> Array<Int4>,
        parent_ingredients -> Array<Int4>,
        gram_protein_per_gram -> Nullable<Float4>,
        gram_carbs_per_gram -> Nullable<Float4>,
        gram_fat_per_gram -> Nullable<Float4>,
        gram_fiber_per_gram -> Nullable<Float4>,
        vitamins -> Nullable<Jsonb>,
        minerals -> Nullable<Jsonb>,
        essential_fatty_acids -> Nullable<Jsonb>,
        essential_amino_acids -> Nullable<Jsonb>,
        heavy_metals -> Nullable<Jsonb>,
        micro_plastics -> Nullable<Jsonb>,
        industrial_chemicals -> Nullable<Jsonb>,
        pesticides -> Nullable<Jsonb>,
        hormones -> Nullable<Jsonb>,
        antibiotics -> Nullable<Jsonb>,
        beta_agonists -> Nullable<Jsonb>,
        antiparasitics -> Nullable<Jsonb>,
        carcinogens -> Nullable<Jsonb>,
        natural_toxins -> Nullable<Jsonb>,
        radiological -> Nullable<Jsonb>,
        historical_issues -> Nullable<Jsonb>,
        fraudulent_ingredients -> Nullable<Jsonb>,
        dyes -> Nullable<Jsonb>,
        emulsifiers -> Nullable<Jsonb>,
        preservatives -> Nullable<Jsonb>,
        gram_trans_fat_per_gram -> Nullable<Float4>,
        created_at -> Timestamp,
        updated_at -> Timestamp,
    }
}

diesel::table! {
    products (id) {
        id -> Int4,
        barcode -> Varchar,
        product_name -> Nullable<Varchar>,
        brands -> Nullable<Varchar>,
        categories -> Nullable<Text>,
        quantity -> Nullable<Varchar>,
        image_url -> Nullable<Text>,
        nutriscore_grade -> Nullable<Varchar>,
        nova_group -> Nullable<Int4>,
        ecoscore_grade -> Nullable<Varchar>,
        ingredients_text -> Nullable<Text>,
        allergens -> Nullable<Text>,
        full_response -> Jsonb,
        created_at -> Timestamp,
        updated_at -> Timestamp,
    }
}

diesel::table! {
    products_non_food (id) {
        id -> Int4,
        barcode -> Nullable<Varchar>,
        upc -> Nullable<Varchar>,
        sku -> Nullable<Varchar>,
        name -> Varchar,
        brand -> Nullable<Varchar>,
        manufacturer -> Nullable<Varchar>,
        model_number -> Nullable<Varchar>,
        category -> Nullable<Varchar>,
        subcategory -> Nullable<Varchar>,
        description -> Nullable<Text>,
        weight_grams -> Nullable<Float4>,
        length_cm -> Nullable<Float4>,
        width_cm -> Nullable<Float4>,
        height_cm -> Nullable<Float4>,
        volume_ml -> Nullable<Float4>,
        color -> Nullable<Varchar>,
        material -> Nullable<Jsonb>,
        size -> Nullable<Varchar>,
        certifications -> Nullable<Jsonb>,
        safety_warnings -> Nullable<Text>,
        age_restriction -> Nullable<Int4>,
        contains_batteries -> Nullable<Bool>,
        hazardous_materials -> Nullable<Jsonb>,
        country_of_origin -> Nullable<Varchar>,
        recyclable -> Nullable<Bool>,
        recycling_info -> Nullable<Text>,
        eco_certifications -> Nullable<Jsonb>,
        sustainability_score -> Nullable<Float4>,
        carbon_footprint_kg -> Nullable<Float4>,
        packaging_type -> Nullable<Varchar>,
        biodegradable -> Nullable<Bool>,
        instructions -> Nullable<Text>,
        care_instructions -> Nullable<Text>,
        warranty_months -> Nullable<Int4>,
        lifespan_estimate_years -> Nullable<Float4>,
        maintenance_schedule -> Nullable<Text>,
        msrp_usd -> Nullable<Float4>,
        current_price_usd -> Nullable<Float4>,
        currency -> Nullable<Varchar>,
        availability -> Nullable<Varchar>,
        release_date -> Nullable<Date>,
        discontinued_date -> Nullable<Date>,
        average_rating -> Nullable<Float4>,
        total_reviews -> Nullable<Int4>,
        images -> Nullable<Jsonb>,
        videos -> Nullable<Jsonb>,
        manuals -> Nullable<Jsonb>,
        features -> Nullable<Jsonb>,
        specifications -> Nullable<Jsonb>,
        compatible_with -> Nullable<Jsonb>,
        alternatives -> Nullable<Jsonb>,
        tags -> Nullable<Jsonb>,
        full_response -> Nullable<Jsonb>,
        data_source -> Nullable<Varchar>,
        created_at -> Timestamp,
        updated_at -> Timestamp,
        last_verified_at -> Nullable<Timestamp>,
    }
}

diesel::allow_tables_to_appear_in_same_query!(
    ingredients,
    products,
    products_non_food,
);
